export const elements = [
    {
        number: 1,
        name: 'Hydrogen',
        weight: 1.0079,
        abbr: 'H',
        feature: 'RNM',
        area: 'first',
    },
    {
        number: 2,
        name: 'Helium',
        weight: 4.0026,
        abbr: 'He',
        feature: 'Noble',
        area: 'third',
    },
    {
        number: 3,
        name: 'Lithium',
        weight: 6.941,
        abbr: 'Li',
        feature: 'Alkali',
        area: "first",
    },
    {
        number: 4,
        name: 'Beryllium',
        weight: 9.0122,
        abbr: 'Be',
        feature: 'AE',
        area: "first",
    },
    {
        number: 5,
        name: 'Boron',
        weight: 10.811,
        abbr: 'B',
        feature: 'Metalloids',
        area: 'third',
    },
    {
        number: 6,
        name: 'Carbon',
        weight: 12.011,
        abbr: 'C',
        feature: 'RNM',
        area: 'third',
    },
    {
        number: 7,
        name: 'Nitrogen',
        weight: 14.007,
        abbr: 'N',
        feature: 'RNM',
        area: 'third',
    },
    {
        number: 8,
        name: 'Oxygen',
        weight: 15.999,
        abbr: 'O',
        feature: 'RNM',
        area: 'third',
    },
    {
        number: 9,
        name: 'Fluorine',
        weight: 18.998,
        abbr: 'F',
        feature: 'RNM',
        area: 'third',
    },
    {
        number: 10,
        name: 'Neon',
        weight: 20.180,
        abbr: 'Ne',
        feature: 'Noble',
        area: 'third',
    },
    {
        number: 11,
        name: 'Sodium',
        weight: 22.990,
        abbr: 'Na',
        feature: 'Alkali',
        area: "first",
    },
    {
        number: 12,
        name: 'Magnesium',
        weight: 24.305,
        abbr: 'Mg',
        feature: 'AE',
        area: "first",
    },
    {
        number: 13,
        name: 'Aluminium',
        weight: 26.982,
        abbr: 'Al',
        area: 'third',
    },
    {
        number: 14,
        name: 'Silicon',
        weight: 28.086,
        abbr: 'Si',
        feature: 'Metalloids',
        area: 'third',
    },
    {
        number: 15,
        name: 'Phosphorus',
        weight: 30.974,
        abbr: 'P',
        feature: 'RNM',
        area: 'third',
    },
    {
        number: 16,
        name: 'Sulfur',
        weight: 32.065,
        abbr: 'S',
        feature: 'RNM',
        area: 'third',
    },
    {
        number: 17,
        name: 'Chlorine',
        weight: 35.453,
        abbr: 'Cl',
        feature: 'RNM',
        area: 'third',
    },
    {
        number: 18,
        name: 'Argon',
        weight: 39.948,
        abbr: 'Ar',
        feature: 'Noble',
        area: 'third',
    },
    {
        number: 19,
        name: 'Potassium',
        weight: 39.098,
        abbr: 'K',
        feature: 'Alkali',
        area: "first",
    },
    {
        number: 20,
        name: 'Calcium',
        weight: 40.078,
        abbr: 'Ca',
        feature: 'AE',
        area: "first",
    },
    {
        number: 21,
        name: 'Scandium',
        weight: 44.956,
        abbr: 'Sc',
        feature: 'Transition',
        area: "first",
    },
    {
        number: 22,
        name: 'Titanium',
        weight: 47.867,
        abbr: 'Ti',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 23,
        name: 'Vanadium',
        weight: 50.942,
        abbr: 'V',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 24,
        name: 'Chromium',
        weight: 51.996,
        abbr: 'Cr',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 25,
        name: 'Manganese',
        weight: 54.938,
        abbr: 'Mn',
        feature: 'Transition',
        area: 'second',

    },
    {
        number: 26,
        name: 'Iron',
        weight: 55.845,
        abbr: 'Fe',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 27,
        name: 'Cobalt',
        weight: 58.933,
        abbr: 'Mn',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 28,
        name: 'Nickel',
        weight: 58.963,
        abbr: 'Ni',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 29,
        name: 'Copper',
        weight: 63.546,
        abbr: 'Cu',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 30,
        name: 'Zinc',
        weight: 65.380,
        abbr: 'Zn',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 31,
        name: 'Gallium',
        weight: 69.723,
        abbr: 'Ga',
        area: 'third',
    },
    {
        number: 32,
        name: 'Germanium',
        weight: 72.640,
        abbr: 'Ge',
        feature: 'Metalloids',
        area: 'third',
    },
    {
        number: 33,
        name: 'Arsenic',
        weight: 74.922,
        abbr: 'As',
        feature: 'Metalloids',
        area: 'third',
    },
    {
        number: 34,
        name: 'Selenium',
        weight: 78.960,
        abbr: 'Se',
        feature: 'RNM',
        area: 'third',
    },
    {
        number: 35,
        name: 'Bromine',
        weight: 79.904,
        abbr: 'Br',
        feature: 'RNM',
        area: 'third',
    }, {
        number: 36,
        name: 'Krypton',
        weight: 83.798,
        abbr: 'Kr',
        feature: 'Noble',
        area: 'third',
    },
    {
        number: 37,
        name: 'Rubidium',
        weight: 85.468,
        abbr: 'Rb',
        feature: 'Alkali',
        area: "first",
    },
    {
        number: 38,
        name: 'Strontium',
        weight: 87.620,
        abbr: 'Sr',
        feature: 'AE',
        area: "first",
    },
    {
        number: 39,
        name: 'Yttrium',
        weight: 88.906,
        abbr: 'Y',
        feature: 'Transition',
        area: "first",
    },
    {
        number: 40,
        name: 'Zirconium',
        weight: 91.224,
        abbr: 'Zr',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 41,
        name: 'Niobium',
        weight: 92.906,
        abbr: 'Nb',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 42,
        name: 'Molybdenum',
        weight: 95.950,
        abbr: 'Mo',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 43,
        name: 'Technetium',
        weight: 98,
        abbr: 'Tc',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 44,
        name: 'Ruthenium',
        weight: 101.07,
        abbr: 'Ru',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 45,
        name: 'Rhodium',
        weight: 102.91,
        abbr: 'Rh',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 46,
        name: 'Palladium',
        weight: 106.42,
        abbr: 'Pd',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 47,
        name: 'Silver',
        weight: 107.87,
        abbr: 'Ag',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 48,
        name: 'Cadmium',
        weight: 112.41,
        abbr: 'Cd',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 49,
        name: 'Indium',
        weight: 114.82,
        abbr: 'In',
        area: 'third',
    },
    {
        number: 50,
        name: 'Tin',
        weight: 118.71,
        abbr: 'Sn',
        area: 'third',
    },
    {
        number: 51,
        name: 'Antimony',
        weight: 121.76,
        abbr: 'Sb',
        feature: 'Metalloids',
        area: 'third',
    },
    {
        number: 52,
        name: 'Tellurium',
        weight: 127.60,
        abbr: 'Sb',
        feature: 'Metalloids',
        area: 'third',
    },
    {
        number: 53,
        name: 'Iodine',
        weight: 126.90,
        abbr: 'I',
        feature: 'RNM',
        area: 'third',
    },
    {
        number: 54,
        name: 'Xenon',
        weight: 131.29,
        abbr: 'Xe',
        feature: 'Noble',
        area: 'third',
    },
    {
        number: 55,
        name: 'Caesium',
        weight: 132.91,
        abbr: 'Cs',
        feature: 'Alkali',
        area: "first",
    },
    {
        number: 56,
        name: 'Barium',
        weight: 137.33,
        abbr: 'Ba',
        feature: 'AE',
        area: "first",
    },
    {
        number: 57,
        name: 'Lanthanum',
        weight: 138.91,
        abbr: 'La',
        area: "first",
    },
    {
        number: 72,
        name: 'Hafnium',
        weight: 178.49,
        abbr: 'Hf',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 73,
        name: 'Tantalum',
        weight: 180.95,
        abbr: 'Ta',
        feature: 'Transition',
        area: 'second',
    }, {
        number: 74,
        name: 'Tungsten',
        weight: 183.84,
        abbr: 'W',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 75,
        name: 'Rhenium',
        weight: 186.21,
        abbr: 'Re',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 76,
        name: 'Osmium',
        weight: 190.23,
        abbr: 'Os',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 77,
        name: 'Iridium',
        weight: 192.22,
        abbr: 'Ir',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 78,
        name: 'Platinum',
        weight: 195.08,
        abbr: 'Pt',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 79,
        name: 'Gold',
        weight: 196.97,
        abbr: 'Au',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 80,
        name: 'Mercury',
        weight: 200.59,
        abbr: 'Hg',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 81,
        name: 'Thallium',
        weight: 204.38,
        abbr: 'Tl',
        area: 'third',
    },
    {
        number: 82,
        name: 'Lead',
        weight: 207.20,
        abbr: 'Pb',
        area: 'third',
    },
    {
        number: 83,
        name: 'Bismuth',
        weight: 208.98,
        abbr: 'Bi',
        area: 'third',
    },
    {
        number: 84,
        name: 'Polonium',
        weight: 209,
        abbr: 'Po',
        area: 'third',
    },
    {
        number: 85,
        name: 'Astatine',
        weight: 210,
        abbr: 'At',
        area: 'third',
    },
    {
        number: 86,
        name: 'Radon',
        weight: 222,
        abbr: 'Rn',
        feature: 'Noble',
        area: 'third',
    },
    {
        number: 87,
        name: 'Francium',
        weight: 223,
        abbr: 'Fr',
        feature: 'Alkali',
        area: "first",
    },
    {
        number: 88,
        name: 'Radium',
        weight: 226,
        abbr: 'Ra',
        feature: 'AE',
        area: "first",
    },
    {
        number: 89,
        name: 'Actinium',
        weight: 227,
        abbr: 'Ac',
        area: "first",
    },
    {
        number: 104,
        name: 'Rutherfordium',
        weight: 267,
        abbr: 'Rf',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 105,
        name: 'Dubnium',
        weight: 262,
        abbr: 'Db',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 106,
        name: 'Seaborgium',
        weight: 269,
        abbr: 'Sg',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 107,
        name: 'Bohrium',
        weight: 264,
        abbr: 'Bh',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 108,
        name: 'Hassium',
        weight: 269,
        abbr: 'Hs',
        feature: 'Transition',
        area: 'second',
    },
    {
        number: 109,
        name: 'Meitnerium',
        weight: 278,
        abbr: 'Mt',
        feature: 'Unknown',
        area: 'second',
    },
    {
        number: 110,
        name: 'Darmstadtium',
        weight: 267,
        abbr: 'Ds',
        feature: 'Unknown',
        area: 'second',
    },
    {
        number: 111,
        name: 'Roentgenium',
        weight: 282,
        abbr: 'Rg',
        feature: 'Unknown',
        area: 'second',
    },
    {
        number: 112,
        name: 'Copernicium',
        weight: 285,
        abbr: 'Cn',
        feature: 'Unknown',
        area: 'second',
    },
    {
        number: 113,
        name: 'Nihonium',
        weight: 286,
        abbr: 'Nh',
        feature: 'Unknown',
        area: 'third',
    },
    {
        number: 114,
        name: 'Flerovium',
        weight: 289,
        abbr: 'Fl',
        feature: 'Unknown',
        area: 'third',
    },
    {
        number: 115,
        name: 'Moscovium',
        weight: 289,
        abbr: 'Mc',
        feature: 'Unknown',
        area: 'third',
    },
    {
        number: 116,
        name: 'Livermorium',
        weight: 293,
        abbr: 'Lv',
        feature: 'Unknown',
        area: 'third',
    },
    {
        number: 117,
        name: 'Tennessine',
        weight: 294,
        abbr: 'Ts',
        feature: 'Unknown',
        area: 'third',
    },
    {
        number: 118,
        name: 'Oganesson',
        weight: 294,
        abbr: 'Og',
        feature: 'Unknown',
        area: 'third',
    },
    {
        number: 58,
        name: 'Cerium',
        weight: 140.12,
        abbr: 'Ce',
        feature: 'lanthanides',
    },
    {
        number: 59,
        name: 'Praseodymium',
        weight: 140.91,
        abbr: 'Pr',
        feature: 'lanthanides',
    },
    {
        number: 60,
        name: 'Neodymium',
        weight: 144.24,
        abbr: 'Nd',
        feature: 'lanthanides',
    },
    {
        number: 61,
        name: 'Promethium',
        weight: 144.24,
        abbr: 'Nd',
        feature: 'lanthanides',
    },
    {
        number: 62,
        name: 'Samarium',
        weight: 150.36,
        abbr: 'Sm',
        feature: 'lanthanides',
    },
    {
        number: 63,
        name: 'Europium',
        weight: 151.96,
        abbr: 'Eu',
        feature: 'lanthanides',
    },
    {
        number: 64,
        name: 'Gadolinium',
        weight: 157.25,
        abbr: 'Gd',
        feature: 'lanthanides',
    },
    {
        number: 65,
        name: 'Terbium',
        weight: 158.93,
        abbr: 'Tb',
        feature: 'lanthanides',
    },
    {
        number: 66,
        name: 'Dysprosium',
        weight: 162.5,
        abbr: 'Dy',
        feature: 'lanthanides',
    },
    {
        number: 67,
        name: 'Holmium',
        weight: 164.93,
        abbr: 'Ho',
        feature: 'lanthanides',
    },
    {
        number: 68,
        name: 'Erbium',
        weight: 167.26,
        abbr: 'Er',
        feature: 'lanthanides',
    },
    {
        number: 69,
        name: 'Thulium',
        weight: 168.93,
        abbr: 'Tm',
        feature: 'lanthanides',
    },
    {
        number: 70,
        name: 'Ytterbium',
        weight: 173.04,
        abbr: 'Yb',
        feature: 'lanthanides',
    },
    {
        number: 71,
        name: 'Lutetium',
        weight: 174.97,
        abbr: 'Lu',
        feature: 'lanthanides',
    },
    {
        number: 90,
        name: 'Thorium',
        weight: 232.04,
        abbr: 'Th',
        feature: 'actinides',
    },
    {
        number: 91,
        name: 'Protactinium',
        weight: 231.04,
        abbr: 'Pa',
        feature: 'actinides',
    },
    {
        number: 92,
        name: 'Uranium',
        weight: 238.03,
        abbr: 'U',
        feature: 'actinides',
    },
    {
        number: 93,
        name: 'Neptunium',
        weight: 237.05,
        abbr: 'Np',
        feature: 'actinides',
    },
    {
        number: 94,
        name: 'Plutonium',
        weight: 244,
        abbr: 'Pu',
        feature: 'actinides',
    },
    {
        number: 95,
        name: 'Americium',
        weight: 243,
        abbr: 'Am',
        feature: 'actinides',
    },
    {
        number: 96,
        name: 'Curium',
        weight: 247,
        abbr: 'Cm',
        feature: 'actinides',
    },
    {
        number: 97,
        name: 'Berkelium',
        weight: 247,
        abbr: 'Bk',
        feature: 'actinides',
    },
    {
        number: 98,
        name: 'Californium',
        weight: 251,
        abbr: 'Cf',
        feature: 'actinides',
    },
    {
        number: 99,
        name: 'Einsteinium',
        weight: 252,
        abbr: 'Es',
        feature: 'actinides',
    },
    {
        number: 100,
        name: 'Fermium',
        weight: 257,
        abbr: 'Fm',
        feature: 'actinides',
    },
    {
        number: 101,
        name: 'Mendelevium',
        weight: 258,
        abbr: 'Md',
        feature: 'actinides',
    },
    {
        number: 102,
        name: 'Nobelium',
        weight: 259,
        abbr: 'No',
        feature: 'actinides',
    },
    {
        number: 103,
        name: 'Lawrencium',
        weight: 262,
        abbr: 'Lr',
        feature: 'actinides',
    },
]
